A2: A2.o A2.cpp modular.h queue.h stack.h compl.h dyn_arr.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC A2.o -o A2
A2.o: A2.cpp modular.h queue.h stack.h compl.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC A2.cpp -c
B2: B2.o B2.cpp modular.h queue.h stack.h compl.h dyn_arr.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC B2.o -o B2
B2.o: A2.cpp modular.h queue.h stack.h compl.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC B2.cpp -c
C2: C2.o C2.cpp modular.h queue.h stack.h compl.h dyn_arr.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC C2.o -o C2
C2.o: C2.cpp modular.h queue.h stack.h compl.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC C2.cpp -c
D2: D2.o D2.cpp modular.h queue.h stack.h compl.h dyn_arr.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC D2.o -o D2
D2.o: D2.cpp modular.h queue.h stack.h compl.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC D2.cpp -c
E2: E2.o E2.cpp modular.h queue.h stack.h compl.h dyn_arr.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC E2.o -o E2
E2.o: E2.cpp modular.h queue.h stack.h compl.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC E2.cpp -c
F2: F2.o F2.cpp modular.h queue.h stack.h compl.h dyn_arr.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC F2.o -o F2
F2.o: F2.cpp modular.h queue.h stack.h compl.h
	g++ -W -Wall -Wfloat-equal -Wpointer-arith -Wwrite-strings -Wcast-align \
	-Wformat-security -Wmissing-format-attribute -Wformat=1 \
	-Wno-long-long -Wcast-align -Winline -Werror -pedantic -pedantic-errors \
	-Wunused -Wuninitialized \
	--param inline-unit-growth=1000000 --param max-inline-insns-single=10000000 \
	--param large-function-growth=10000000 -fPIC F2.cpp -c
clear:
	rm -f *.o